### ISSUE TITLE
todo: session 08 (GitHub Intro)

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-course-uhh-ss24#22]
- [x] Sent Email regarding creating github account
- [x]  Create good exercises (pushing repo (main branch), Optional push all branches not merged delete the rest,  Optional: clone own repo to different location on computer)
- [x] Slides: all people who have repo in user directory say sth, 
- [x] Slides: make repo private and add lennart and Konrad as collaborators 
- [x] Create Organization and fork repos in there

**Comment by lnnrtwttkhn** [comment]
all fixed by #23. closing.
